language: php
dist: trusty
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: UPDATE_COVERAGE=1
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: hhvm
  allow_failures:
    - php: hhvm
  fast_finish: true
before_script:
  - sh -c "[ -z $UPDATE_COVERAGE ] && phpenv config-rm xdebug.ini || true"
script:
- ./build.sh
